image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          - mvn --version
          - mvn -B -P wiremock-1.57 clean verify
          - mvn -B -P wiremock-2.5 clean verify
          - mvn -B -P wiremock-2.11 clean verify javadoc:jar
